-- Auto-generated from services/chatbot/src/data/item-catalog.json
-- Run: node db/generate-doc-registry-seed.mjs > db/seed-docs.sql
--
-- Populates document_registry with the full item catalog (168 items).
-- Uses ON CONFLICT to upsert so existing FK references are preserved.
-- Old entries not in the catalog are left in place (orphan-safe).

INSERT INTO document_registry (doc_id, name, description, alternatives) VALUES
  ('primary-id-passport', 'US passport (original, unexpired)', 'Accepted primary identity document for REAL ID.', '{}'),
  ('primary-id-birth-certificate', 'Certified US birth certificate (original, with raised seal)', 'Must be certified with seal. Hospital souvenir certificates not accepted.', '{}'),
  ('primary-id-naturalization-cert', 'Certificate of Naturalization (N-550 / N-570)', '', '{}'),
  ('primary-id-citizenship-cert', 'Certificate of Citizenship (N-560 / N-561)', '', '{}'),
  ('primary-id-consular-report', 'Consular Report of Birth Abroad (FS-240 / DS-1350 / FS-545)', '', '{}'),
  ('lawful-presence-green-card', 'Permanent Resident Card (I-551 / green card)', '', '{}'),
  ('lawful-presence-visa-i94', 'Valid visa with passport and I-94 (and EAD if applicable)', '', '{}'),
  ('social-security-card', 'Original Social Security card — or an accepted SSN alternative (see notes)', 'The original card is preferred, but if you don''t have it the office routinely accepts an alternative that shows your SSN: a W-2, any 1099 form, Form 1095-C, a pay stub, or the office''s self-certification of Social Security number. (Source: tcslc-sme policy-questions DL-1, 2026-07.)', '{}'),
  ('address-proof-1', 'Proof of St. Lucie County residential address #1 (deed, mortgage statement, lease, current utility bill, voter registration card, bank statement, or official mail dated within 60 days)', 'FLHSMV requires TWO proofs of Florida residential address, each from a different source. Must show residency of more than 30 days and be dated within 60 days.', '{}'),
  ('address-proof-2', 'Proof of St. Lucie County residential address #2 (from a different source than #1)', 'FLHSMV requires two documents from different sources.', '{}'),
  ('declaration-of-domicile', 'Declaration of Domicile from the St. Lucie County Clerk of the Circuit Court — substitutes for one of the required proofs of FL address', 'FLHSMV requires TWO proofs of Florida residential address (from different sources). This Declaration of Domicile substitutes for a proof you''re missing. Get it from the Clerk of Court''s Recording Department: fill it out, get it notarized, then record it at the Clerk''s office before your tax collector visit.', '{}'),
  ('name-change-marriage-cert', 'Certified marriage certificate (for name change; church-issued not accepted)', '', '{}'),
  ('name-change-divorce-decree', 'Certified divorce decree (for name change)', '', '{}'),
  ('name-change-court-order', 'Certified court order of name change', '', '{}'),
  ('oos-license', 'Current out-of-state driver license', '', '{}'),
  ('certified-driving-record', 'Certified driving record from prior state (required when license cannot be verified in NLETS)', '', '{}'),
  ('vision-test-or-dl10', 'Corrective lenses (if needed) OR completed HSMV 72010 Report of Eye Examination', '', '{}'),
  ('military-orders', 'Copy of military orders (active-duty service members)', '', '{}'),
  ('hsmv-82040', 'Application for Certificate of Title (HSMV 82040)', '', '{}'),
  ('hsmv-82042', 'VIN and Odometer Verification (HSMV 82042)', 'Required for out-of-state vehicles. Must be completed by FL DMV compliance examiner, FL licensed dealer, FL notary, law enforcement officer, or US Military Police. Not required if vehicle is brought to the office parking lot for on-site VIN verification.', '{}'),
  ('hsmv-82053', 'Power of Attorney for a Motor Vehicle, Mobile Home, Vessel, or Vessel with Trailer (HSMV 82053)', '', '{}'),
  ('hsmv-82050', 'Notice of Sale / Bill of Sale (HSMV 82050)', 'Required when purchaser name is missing from the title assignment or when odometer disclosure needs a separate document.', '{}'),
  ('original-vehicle-title', 'Original vehicle title, signed by all registered owners (photocopies not accepted)', '', '{}'),
  ('oos-registration', 'Current out-of-state registration (dated within the last 6 months)', '', '{}'),
  ('bill-of-sale-purchase-agreement', 'Bill of sale or purchase agreement', 'Used to prove sales tax paid out of state (if owned less than 6 months) and/or to supply odometer disclosure when the title is missing it.', '{}'),
  ('proof-oos-sales-tax', 'Proof of sales tax paid in previous state (bill of sale, dealer invoice, or tax receipt)', 'Applies only when vehicle owned less than 6 months. Without proof, FL collects full 6% Use Tax + local option tax.', '{}'),
  ('lien-letter', 'Lienholder letter on letterhead with VIN, make, and year (or copy of OOS title showing the lien)', '', '{}'),
  ('lease-agreement-with-lessor-letter', 'Lease agreement plus lessor letter authorizing Florida ''Registration Only'' (VIN, make, and year must appear in the letter)', '', '{}'),
  ('fl-insurance-proof', 'Proof of current Florida PDL and PIP insurance (insurance ID card with company name + policy number; the VIN of the vehicle must be listed on the policy)', '', '{}'),
  ('sunbiz-registration', 'Sunbiz ''active'' registration printout for the business (showing registered agents)', 'Required when title will be in a business name.', '{}'),
  ('certification-of-trust', 'Certification of Trust or full Trust Agreement', 'Required when title will be held in a trust.', '{}'),
  ('all-trustees-present-or-poa', 'All trustees present in person OR power of attorney for absent trustees', '', '{}'),
  ('adult-co-purchaser-present', 'Adult (18+) co-purchaser present to sign the title application', 'Required when the primary purchaser is a minor.', '{}'),
  ('all-applicants-present', 'All applicants present with their government-issued photo ID', '', '{}'),
  ('photo-id-all-applicants', 'Valid government-issued photo ID for each person signing', '', '{}'),
  ('fl-driver-license', 'Current Florida driver license or ID', '', '{}'),
  ('cdl-medical-cert-uploaded', 'DOT medical examiner''s certificate uploaded to the Florida system (by the examining physician''s office)', 'FL cannot accept the paper card at the counter; the physician''s office must upload it to the state system.', '{}'),
  ('cdl-general-knowledge-exam', 'Pass the CDL General Knowledge written exam (in English, cannot be taken in audio form)', '', '{}'),
  ('cdl-skills-exam', 'Pass the CDL skills (driving) exam', 'Not eligible until CLP has been held for 2 weeks.', '{}'),
  ('cdl-application-fee', 'CDL application fee ($75, plus $7 per endorsement)', '', '{}'),
  ('cdl-late-fee', 'CDL late fee (required when CDL has been expired less than 1 year)', '', '{}'),
  ('hazmat-tsa-fee', 'TSA background check fee for hazmat endorsement ($91)', '', '{}'),
  ('hazmat-written-test', 'Pass the Hazmat written test (valid only 60 days; available in English or Spanish; may be taken in audio form)', 'Hazmat fingerprinting is not available at the Walton Road office (no fingerprint machine). Hazmat testing and fingerprinting are handled ONLY at the Tradition and Fort Pierce offices. (Source: tcslc-sme policy-questions CDL-1, 2026-07.)', '{}'),
  ('school-employee-letter-or-id', 'School employment ID card OR letter from the school department on letterhead', 'For any school-district employee required to hold a CDL (NOT limited to school-bus endorsement applicants). Required on every original and every renewal and scanned into the record; qualifies the customer for the reduced school-employee CDL fee. (Source: tcslc-sme policy-questions CDL-2, 2026-07.)', '{}'),
  ('valid-out-of-state-cdl', 'Valid out-of-state CDL (from a US state or territory)', '', '{}'),
  ('cdl-endorsement-fee-per', '$7 endorsement fee for each CDL endorsement requested', '', '{}'),
  ('poa-document', 'Power of attorney authorizing someone other than the owner to sign the title paperwork (a general, durable, or limited POA is accepted — the HSMV 82053 form is NOT required)', 'Any general, durable, or limited POA is accepted as long as it grants authority to conduct the requested motor-vehicle transaction — HSMV 82053 is one option, not a requirement. A POA executed on or after 2011-10-01 must be signed by the principal, include two witnesses, and be notarized OR contain a perjury clause in lieu of notarization. If a durable POA is used to title the vehicle into the appointee''s own name, the ORIGINAL durable POA is required. [Confirmed by TCSLC staff — policy-questions TITLE-6, 2026-07.]', '{}'),
  ('odometer-disclosure-bill-of-sale', 'Odometer disclosure — completed on HSMV 82050 bill of sale if not present on the title', '', '{}'),
  ('fl-driver-license-to-renew', 'Current Florida driver license or ID card (the credential you are renewing)', '', '{}'),
  ('mydmv-portal-referral', 'Renew online at MyDMV Portal (https://mydmvportal.flhsmv.gov/). Credential mailed within 2-3 weeks. $2 online processing fee applies in addition to the renewal fee.', 'Only offered every other renewal cycle per FLHSMV policy. If customer used online last time, they must come in-office.', '{}'),
  ('dd214-or-veteran-id', 'DD-214 discharge document (any member-copy) or VA-issued veteran ID card to add the ''V'' designation', '', '{}'),
  ('va-100-percent-disability-letter', 'VA letter documenting 100% total and permanent service-connected disability rating (required for no-fee credential per §322.21)', '', '{}'),
  ('ssa-record-updated', 'Confirmation that your Social Security Administration record already reflects your new name (FLHSMV will cross-check this at the counter; visit SSA before your office appointment if not yet done)', 'Pre-requisite task, not a document — the customer must have visited the Social Security Administration and updated their name before coming to the tax collector. SSA card does not need to be presented (only original one for REAL ID verification).', '{}'),
  ('tlsae-course-completion', 'Proof of completion of the Traffic Law & Substance Abuse Education (TLSAE) or Driver Education Traffic Safety (DETS) course from an FLHSMV-approved provider', 'Approved providers report completion electronically to FLHSMV; no physical certificate required at counter. Required for any first-time licensee who has never held a DL in any state or country.', '{}'),
  ('parent-proctoring-form', 'Parent Proctoring Form (HSMV 71144) — notarized OR signed in front of a driver license examiner — for online Class E knowledge exam by applicants under 18', '', '{}'),
  ('parent-consent-form', 'Parental Consent for Driver Application of a Minor (HSMV 71142) — signed with parent/guardian present, in office', '', '{}'),
  ('parent-id-valid', 'Parent or legal guardian must bring a valid government-issued photo ID to co-sign for the minor applicant', '', '{}'),
  ('cdl-general-knowledge-exam-scheduling', 'Schedule the in-office Class E knowledge exam (50 questions, 80% required to pass, English only) at your driver license service center', 'Not a document — an in-office exam appointment. $30 first-attempt fee (standard Class E learner application).', '{}'),
  ('current-registration-or-renewal-notice', 'Current or most-recent vehicle registration OR renewal notice (copy acceptable)', '', '{}'),
  ('hvut-2290-proof', 'IRS Form 2290 showing the Heavy Vehicle Use Tax has been paid (or proof of exemption, e.g., vehicle purchased within 60 days)', 'Required for vehicles with GVW of 55,000 lbs or more. Must match the VIN on registration and insurance; no alterations accepted.', '{}'),
  ('commercial-insurance-limits-proof', 'Commercial-vehicle insurance policy with correct coverage limits (ACORD Form, Certificate of Liability, or FMCSA Self-Insurance proof)', '', '{}'),
  ('military-insurance-affidavit', 'Military Insurance Exemption Affidavit (HSMV 71061) for active-duty service members using out-of-state insurance', '', '{}'),
  ('oos-title-surrender', 'Physical out-of-state vehicle title for surrender to Florida', '', '{}'),
  ('vin-verification-completed', 'VIN verification (HSMV 82042) — can be completed in-office by the clerk, or in advance by law enforcement, a Florida notary, or a licensed dealer', '', '{}'),
  ('customs-import-documents', 'US Customs import documentation for foreign-country vehicles — EPA 3520-1, DOT HS-7, CBP 7501 entry summary', '', '{}'),
  ('hsmv-82002', 'Initial Registration Fee Exemption Affidavit (HSMV 82002) — signed by applicant for §320.072 exemption', '', '{}'),
  ('death-certificate', 'Certified death certificate of the deceased spouse (for surviving-spouse exemption)', '', '{}'),
  ('existing-physical-plate-or-number', 'The existing physical license plate you are transferring (or the plate number if the plate is not in hand)', '', '{}'),
  ('specialty-plate-packet-guide', 'Florida Specialty License Plate packet — review available plates and eligibility requirements', '', '{}'),
  ('va-summary-of-benefits-letter', 'VA Summary of Benefits letter specifying either (1) 100% service-connected disability, (2) compensated at the 100% rate, OR (3) DVA-financed vehicle purchase', '', '{}'),
  ('hsmv-83146', 'Application for Replacement License Plate, Decal, or Parking Permit (HSMV 83146) — must be signed by owner', '', '{}'),
  ('police-report-or-case-number', 'Police report OR police business card with case number documenting the theft', '', '{}'),
  ('physical-license-plate-for-surrender', 'The physical license plate being surrendered', '', '{}'),
  ('license-plate-surrender-affidavit', 'License Plate Surrender Affidavit — signed at the office by the individual surrendering the plate', '', '{}'),
  ('lpsa-signed-by-registered-owner', 'License Plate Surrender Affidavit pre-signed by the registered owner/co-owner (if not surrendering in person)', '', '{}'),
  ('recipient-plate-or-license-info', 'The gift recipient''s name AND either their license plate number or their driver license number', '', '{}'),
  ('hsmv-82101', 'Application for Duplicate or Lost-in-Transit / Reassignment of a Motor Vehicle, Mobile Home or Vessel Title Certificate (HSMV 82101)', 'Used for duplicate titles. Must be signed by all owners if title is joined by ''and''.', '{}'),
  ('mco-or-signed-title', 'Manufacturer''s Certificate of Origin (for new vehicles from a dealer) OR properly signed-over out-of-state title', '', '{}'),
  ('hsmv-83039', 'Application for Disabled Person Parking Permit (HSMV 83039) — top section by you; medical certification by a physician (MD/DO), physician assistant, chiropractor, podiatrist, advanced-practice RN, or optometrist (sight conditions only). Signature must be dated within the last 12 months.', '', '{}'),
  ('existing-placard-number', 'Existing parking-placard number (for renewal tracking)', '', '{}'),
  ('florida-dl-or-id', 'Your Florida driver license or Florida ID card', '', '{}'),
  ('visitor-acceptable-photo-id', 'Photo ID (any one): driver license or ID from your state of residence; valid US passport or passport card; or a DL/ID from American Samoa, Guam, the Northern Marianas, Puerto Rico, or the US Virgin Islands', '', '{}'),
  ('expiring-placard-registration-copy', 'Copy of the registration for your expiring parking permit', 'Required for renewals — the F-83039 Renewal Instructions list this alongside a fresh medical certification.', '{}'),
  ('va-form-letter-27-333', 'VA Form Letter 27-333 (or equivalent), issued in the last 12 months, certifying permanent and total service-connected disability — substitutes for the HSMV 83039 medical certification at renewal or replacement only', '', '{}'),
  ('police-report-stolen-placard', 'Police report listing the stolen placard (waives the $1 replacement fee)', '', '{}'),
  ('home-country-permit-copy', 'Copy of your current parking permit issued by your country of residence', 'Out-of-country visitors may submit this in lieu of HSMV 83039''s medical certification section. Requires BOTH sides — the resident uploads a front and a back image.', '{}'),
  ('org-feid-or-fl-sales-tax', 'Organization''s federal employer ID (FEID) OR Florida sales-tax registration number — one of these is required and will be affixed to the permit', 'Sunbiz registration is NOT an accepted identifier for placard organizational applicants — use FEID or FL sales-tax number only.', '{}'),
  ('payment-15-original-temporary', 'Payment: $15 for the temporary placard (cash, check, or card accepted)', '', '{}'),
  ('payment-15-visitor-temporary', 'Payment: $15 for the visitor temporary placard', '', '{}'),
  ('payment-1-replacement', 'Payment: $1 replacement fee', '', '{}'),
  ('vessel-title-or-mco-or-bill-of-sale', 'Vessel title, Manufacturer''s Certificate of Origin, or bill of sale proving ownership', '', '{}'),
  ('vessel-hull-id-documented', 'Vessel Hull Identification Number (HIN) — verified via HSMV 87183 if not clearly documented on the title', '', '{}'),
  ('oos-vessel-title-surrender', 'Physical out-of-state vessel title to surrender to Florida', '', '{}'),
  ('hsmv-87243', 'Certification for an Antique Vessel Registration (HSMV 87243)', '', '{}'),
  ('hsmv-87244', 'Application to Register Non-Titled Vessels (HSMV 87244)', '', '{}'),
  ('vehicle-for-road-test', 'A vehicle for the road test — must be registered, insured, and in safe operating condition', '', '{}'),
  ('fl-insurance-proof-for-test-vehicle', 'Proof of current Florida insurance on the vehicle being used for the road test', '', '{}'),
  ('walton-road-test-parking-guide', 'Walton Road office — road-test parking guide PDF', '', '{}'),
  ('tradition-road-test-parking-guide', 'Tradition office — road-test parking guide PDF', '', '{}'),
  ('ft-pierce-road-test-parking-guide', 'Ft. Pierce office — road-test parking guide PDF', '', '{}'),
  ('property-tax-bill-or-parcel-number', 'Your property tax bill OR parcel number', '', '{}'),
  ('guaranteed-funds-only', 'Guaranteed funds (cashier''s check, cash, debit, or credit) — personal checks NOT accepted for delinquent taxes', '', '{}'),
  ('dr-534-installment-application', 'Application for Installment Payment of Property Taxes (DR-534) — must be signed by owner, returned by April 30', '', '{}'),
  ('partial-payment-affidavit', 'Partial Payment Affidavit for property taxes — minimum $100 per payment, up to 3 payments, no discounts apply', '', '{}'),
  ('paslc-address-change-form', 'Property Appraiser Address Change Request form (from paslc.gov) — submitted FIRST', '', '{}'),
  ('tcslc-address-change-form', 'Tax Collector Real Estate Change of Address form (tcslc.com) — submitted AFTER the Property Appraiser form', '', '{}'),
  ('personal-check-ok', 'Personal check accepted for current-year tax payments (not for delinquent taxes)', '', '{}'),
  ('fl-discount-schedule', 'Florida property-tax discount schedule (4% Nov, 3% Dec, 2% Jan, 1% Feb, 0% Mar)', '', '{}'),
  ('existing-mobile-home-registration-and-decal', 'Current mobile home registration and decal number (for decal transfer)', '', '{}'),
  ('dr-402-real-property-declaration', 'Declaration of Mobile Home as Real Property (DR-402) — issued by the St. Lucie County Property Appraiser BEFORE applying for an RP decal', '', '{}'),
  ('rp-decal-note', 'Apply for a Real Property (RP) decal at the tax collector — $5.10, permanent as long as the mobile home is not moved', '', '{}'),
  ('mobile-home-title-retirement-application', 'Application for Retirement of a Mobile Home Certificate of Title — HSMV 82109 (separate application required for each unit of a double- or triple-wide)', '', '{}'),
  ('clerk-recorded-documents', 'Copy of documents recorded with the Clerk of Circuit Court (after the Clerk has completed recording)', '', '{}'),
  ('all-tangible-taxes-paid', 'All tangible personal property tax bills paid in full — the title retirement transaction cannot proceed while any tangible tax is owed', '', '{}'),
  ('ccw-firearms-training-document', 'Firearms-training certificate (NRA firearms safety/training course, hunter safety/education course, law-enforcement firearms course, state-certified instructor course, or organized shooting competition documentation) — must include applicant name, instructor name, instructor qualifications and license/certification number', '', '{}'),
  ('ccw-application-fee', 'FDACS CCW license fee (payment by check/money order or the payment methods accepted by your tax collector — regional offices don''t accept cash; tax collectors may charge an additional convenience fee of up to $22)', '', '{}'),
  ('existing-ccw-license', 'Current Florida concealed-weapon license (for renewal)', '', '{}'),
  ('dd214-or-military-orders', 'DD-214 (for honorably-discharged veterans) OR current call-to-active-duty orders and statement of military service (for active-duty servicemembers age 18-20)', '', '{}'),
  ('fwc-license-fee', 'FWC license fee (varies by category and duration — see myfwc.com)', '', '{}'),
  ('disabled-person-hunt-fish-certification', 'Florida Resident Disabled Person''s Hunting and Fishing License certification (no-fee; for residents certified as totally and permanently disabled)', '', '{}'),
  ('military-gold-sportsman-application', 'Military Gold Sportsman''s License application (present current military ID at the tax collector)', '', '{}'),
  ('btr-application-fee', 'Business Tax Receipt application fee (amount varies by classification — apply online at stlucie.county-taxes.com/btexpress for exact amount)', '', '{}'),
  ('existing-btr-account-number', 'Your existing BTR account number (search by business name at stlucie.county-taxes.com to locate)', '', '{}'),
  ('btr-closure-form', 'Business Tax Receipt Closure JotForm (linked from tcslc.com /227/Local-Business-Tax)', '', '{}'),
  ('city-btr-port-st-lucie', 'City of Port St. Lucie Business Tax receipt (772-344-4356 — cityofpsl.com/government/departments/financial-management-department/business-tax-division)', '', '{}'),
  ('city-btr-fort-pierce', 'City of Fort Pierce Certificate of Use (772-467-3065 — cityoffortpierce.com/141/Applications-and-Forms)', '', '{}'),
  ('city-btr-st-lucie-village', 'St. Lucie Village Business Tax receipt (772-466-6900 — stlucievillagefl.gov/online-forms/)', '', '{}'),
  ('slc-zoning-approval', 'St. Lucie County Zoning approval (stluciecountyfl-energovpub.tylerhost.net — call 772-462-2822)', '', '{}'),
  ('slc-fire-inspection', 'St. Lucie County Fire District inspection for commercial locations (772-621-3377 — slcfd.com)', '', '{}'),
  ('state-professional-license', 'State-issued professional license appropriate to your regulated profession (DBPR, FDACS, DOH, etc.)', '', '{}'),
  ('fdacs-pest-control-certification', 'FDACS pest-control / lawn & landscape certification (Florida Dept. of Agriculture — St. Lucie Extension 772-462-1660 — fdacs.gov/Business-Services/Pest-Control/Licensing-and-Certification)', '', '{}'),
  ('btr-exemption-form', 'Business Tax Receipt Exemption Form (DocumentCenter/View/257)', '', '{}'),
  ('nonprofit-501c3-proof', 'Federal 501(c)(3) determination letter or equivalent proof of nonprofit status', '', '{}'),
  ('property-parcel-info', 'Rental property parcel number or folio (from the St. Lucie County Property Appraiser)', '', '{}'),
  ('fdor-sales-tax-registration', 'Florida Department of Revenue sales-tax registration (call 772-429-2900 or visit floridarevenue.com)', '', '{}'),
  ('touristexpress-application', 'TouristExpress new-account application — visit stlucie.county-taxes.com/tourist, click "Add account", follow the application wizard', '', '{}'),
  ('touristexpress-referral', 'File TDT returns monthly at stlucie.county-taxes.com/tourist (2.5% collection allowance, capped at $30/month, if filed by the 20th)', '', '{}'),
  ('tourist-inactive-form', 'Tourist-Tax Inactive form — marks a rental property''s TDT account inactive', '', '{}'),
  ('tourist-owner-agent-agreement', 'Tourist Owner-Agent Agreement — authorizes a property management company to file TDT returns on the owner''s behalf (request via tcslc.com/233/Tourist-Development)', '', '{}'),
  ('dealer-license-active', 'Active Florida motor-vehicle dealer license from FLHSMV (required on file; verify current before drop-off)', '', '{}'),
  ('hsmv-82091', 'Reassignment Supplement to a Certificate of Title (HSMV 82091)', '', '{}'),
  ('hsmv-83090', 'Application by Florida Dealer for Temporary License Plates (HSMV 83090)', '', '{}'),
  ('hsmv-83091', 'Application for Temporary License Plate (HSMV 83091) — per-customer', '', '{}'),
  ('hsmv-82012', 'Application for Towing and Storage Certification of Destruction (HSMV 82012)', '', '{}'),
  ('hsmv-86060', 'Statement of Intent to Relinquish a Dealer License (HSMV 86060)', '', '{}'),
  ('hsmv-82993', 'Separate Odometer Disclosure (HSMV 82993) — used when the title doesn''t include the odometer section', '', '{}'),
  ('reinstatement-fee', 'Driver license reinstatement fee (amount varies by sanction type — see flhsmv.gov/fees/)', '', '{}'),
  ('sr22-filing-from-insurer', 'SR-22 insurance filing — obtained from your auto insurance company and filed electronically with FLHSMV (not hand-carried)', '', '{}'),
  ('licensed-dui-program-completion', 'Licensed DUI Program completion certificate (from an FLHSMV-approved Licensed DUI Program)', '', '{}'),
  ('hardship-license-application', 'Hardship license application — submitted through your local FLHSMV Administrative Reviews Office (not the tax collector). Restricts driving to employment/business purposes only.', '', '{}'),
  ('adi-course-completion', 'Advanced Driver Improvement (ADI) course completion certificate (or enrollment proof if mid-course). Required for HTO, non-DUI serious-injury, and DUI hardship paths.', '', '{}'),
  ('iid-installation-proof', 'Ignition Interlock Device (IID) installation proof from an FLHSMV-contracted provider (per §322.2715)', '', '{}'),
  ('medical-vision-clearance', 'FLHSMV Medical Review clearance (HSMV 72010 eye exam OR Medical Advisory Board clearance letter)', '', '{}'),
  ('tpp-bill-or-account', 'Tangible Personal Property (TPP) tax bill or account number', '', '{}'),
  ('hsmv-82105', 'Certified Official Weight Affidavit (HSMV 82105) — required for trailers and homemade vehicles since registration fees are weight-tiered', '', '{}'),
  ('lsv-equipment-cert', 'Low-Speed Vehicle equipment compliance certification (showing the LSV meets §316.2122 requirements: headlamps, brake lamps, mirrors, windshield, seatbelts)', '', '{}'),
  ('hsmv-84490', 'Statement of Builder (HSMV 84490) — declares you built the vehicle yourself', '', '{}'),
  ('builder-receipts', 'Receipts and bill of materials for parts purchased to build the vehicle (used to calculate sales tax basis)', 'Sales tax on a homemade vehicle is calculated from the cost of materials, not a purchase price.', '{}'),
  ('btr-online-referral', 'Apply online at https://stlucie.county-taxes.com/btexpress — fees are calculated automatically based on the business classification you select.', '', '{}'),
  ('tdt-online-referral', 'File online at the St. Lucie Tourist Development Tax portal (stlucie.county-taxes.com/tourist) — quarterly returns and payments are processed electronically.', '', '{}'),
  ('business-entity-proof', 'Proof of business entity — any one of: FEID number, FL sales-tax registration number, or Sunbiz active-registration printout', '', '{}'),
  ('trust-certification', 'Trust certification or trust agreement showing the trustee''s authority to transfer title', '', '{}'),
  ('certified-weight-slip', 'Certified weight slip from a public scale (CAT scale at a truck stop, county weigh station, or commercial scale) showing the trailer''s empty net weight', 'Required for any trailer registration. The 2,000-lb cutoff between registration-only and title-required is determined by this slip. CAT scales at most truck stops will provide one for ~$15.', '{}'),
  ('parts-receipts-trailer', 'Receipts for parts purchased to build the trailer (frame, axles, wheels, lights, hitch, hardware) — used to calculate 6% sales tax basis', 'Florida charges 6% sales tax on the total material cost for homemade trailers. Bring every receipt you have. If receipts are incomplete, the office may estimate from market value at clerk''s discretion.', '{}'),
  ('prior-owner-bill-of-sale-trailer', 'Bill of sale signed by the previous owner showing trailer description (make/model/year/VIN if any), purchase price, and date', 'Used to calculate 6% sales tax basis on a private-purchase trailer. For trailers <2,000 lb, this is the primary proof of ownership (no title exists).', '{}'),
  ('dealer-bill-of-sale-trailer', 'Dealer bill of sale showing trailer description, purchase price, and dealer-collected sales tax', 'Dealers collect FL sales tax at point of sale and provide a bill of sale showing the breakdown. Tax collector verifies tax was collected; otherwise calculates and collects at the counter.', '{}'),
  ('prior-fl-title-signed-by-seller', 'Original Florida trailer title from the prior owner, signed over to the customer (photocopies not accepted)', 'Required for trailers ≥2,000 lb that already have a Florida title. Seller signs the back; customer brings to tax collector.', '{}'),
  ('death-certificate-inheritance', 'Certified death certificate of the owner named on the title', 'Inheritance/deceased-owner title transfer. Confirmed by St. Lucie tax-office testers (tax423/tax424) as required to establish the owner is deceased. The ADDITIONAL estate documents beyond the death certificate (will, Letters of Administration, FLHSMV decedent affidavit) depend on the survivorship / will / probate path and are confirmed at the counter — see vehicle-title-transfer.review.md for the per-path checklist still to be finalized with the office.', '{}')
ON CONFLICT (doc_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description;
